name = "Jostream"
author = "Fauli1221"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3b2ed04e31b58ca8665b8cf651ce04be5e730e9dfe4ab4142f5ac251a2d22a9"

[versions]
fabric = "0.14.19"
minecraft = "1.19.3"
