name = "Jostream"
author = "Fauli1221"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d866ffd4c226d078d56c823bea577ca1f92f1c80ff930b34fc924c005c27189"

[versions]
fabric = "0.14.19"
minecraft = "1.19.3"
