name = "Jostream"
author = "Fauli1221"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1719d607a17727da42121dd3bde7b3bdbdb7d67fbc82920195224888b95ea377"

[versions]
fabric = "0.14.19"
minecraft = "1.19.3"
