name = "Jostream"
author = "Fauli1221"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8ac8cfdc7b25ffd3a9770caa3042ea3e31c936a75f415d01633d583a49f8822"

[versions]
fabric = "0.14.19"
minecraft = "1.19.3"
