name = "Jostream"
author = "Fauli1221"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0ed1501f5eb83f8dc1657581817001a41a9aa709c181d726249c68f8425fcf3"

[versions]
fabric = "0.14.19"
minecraft = "1.19.3"
